from __future__ import annotations

from typing import Any, Protocol


class GimpBackend(Protocol):
    name: str

    def doctor(self) -> dict[str, Any]: ...
    def seed_demo(self) -> dict[str, Any]: ...
    def list_images(self) -> list[dict[str, Any]]: ...
    def new_image(self, width: int, height: int, color: str = "#ffffff") -> dict[str, Any]: ...
    def open_image(self, path: str) -> dict[str, Any]: ...
    def info(self, image_id: str) -> dict[str, Any]: ...
    def resize(self, image_id: str, width: int, height: int) -> dict[str, Any]: ...
    def crop(
        self, image_id: str, x: int, y: int, width: int, height: int
    ) -> dict[str, Any]: ...
    def flip(self, image_id: str, direction: str = "horizontal") -> dict[str, Any]: ...
    def rotate(self, image_id: str, degrees: float = 90) -> dict[str, Any]: ...
    def blur(self, image_id: str, radius: float = 2.0) -> dict[str, Any]: ...
    def desaturate(self, image_id: str) -> dict[str, Any]: ...
    def invert(self, image_id: str) -> dict[str, Any]: ...
    def text_overlay(
        self,
        image_id: str,
        text: str,
        x: int = 10,
        y: int = 10,
        size: int = 32,
        color: str = "#000000",
    ) -> dict[str, Any]: ...
    def export(self, image_id: str, path: str, format: str | None = None) -> dict[str, Any]: ...
    def batch_resize(
        self, input_dir: str, output_dir: str, width: int, height: int
    ) -> dict[str, Any]: ...
